- hosts: all
  gather_facts: False
  remote_user: root
  sudo: yes
  vars:
     env: develop
     key: 2dd34f62eee0a309fb3e61e3f333a4329a648010
  tasks:
  - name: Install pip package from yum
    yum: name={{ item }} state=present update_cache=true
    with_items:
    - python-pip
    - python-setuptools

  - name: Remove PIP temp directory
    file: path=/tmp/pip-build-root state=absent

  - name: Install PIP required packages
    pip: name={{ item }} state=present
    with_items:
    - argparse
    - pygithub
    - requests

  - name: Transfer the script
    copy: src=scripts/deploy.py dest=/tmp/deploy.py owner=root group=root mode=700 backup=no

  - name: Execute the script
    command: python /tmp/deploy.py {{env}} {{key}}
